/* Erzeugt von scripts/make-plan-fixture.ts — nicht von Hand bearbeiten. */

import type { GuideCardView, ProjectSchedule } from '@meinbaulotse/shared';

export const PLAN_FIXTURE: ProjectSchedule = {
  "project": {
    "id": "00000000-0000-4000-8000-000000000001",
    "name": "Musterweg 4",
    "federalState": "BY",
    "buildType": "efh_massiv",
    "contractType": "verbraucherbauvertrag",
    "hasBasement": true,
    "plannedStart": "2026-04-01",
    "contractualCompletion": "2026-09-30",
    "role": "owner",
    "catholicMunicipality": false
  },
  "permissions": [
    "project.read",
    "project.delete",
    "member.invite",
    "task.write",
    "task.schedule",
    "task.confirm",
    "task.progress",
    "decision.write",
    "diary.write",
    "defect.write",
    "defect.resolve",
    "payment.release",
    "contract.write",
    "export.run"
  ],
  "phases": [
    {
      "key": "vorbereitung",
      "name": "Vorbereitung und Vertrag",
      "ordinal": 1,
      "taskCount": 3,
      "firstStart": "2026-04-01",
      "lastEnd": "2026-04-16"
    },
    {
      "key": "gruendung",
      "name": "Gründung und Keller",
      "ordinal": 2,
      "taskCount": 8,
      "firstStart": "2026-04-08",
      "lastEnd": "2026-05-20"
    },
    {
      "key": "rohbau",
      "name": "Rohbau",
      "ordinal": 3,
      "taskCount": 4,
      "firstStart": "2026-05-13",
      "lastEnd": "2026-06-12"
    },
    {
      "key": "dach_huelle",
      "name": "Dach und Gebäudehülle",
      "ordinal": 4,
      "taskCount": 4,
      "firstStart": "2026-06-15",
      "lastEnd": "2026-06-29"
    },
    {
      "key": "rohinstallation",
      "name": "Rohinstallationen",
      "ordinal": 5,
      "taskCount": 4,
      "firstStart": "2026-06-30",
      "lastEnd": "2026-07-16"
    },
    {
      "key": "ausbau",
      "name": "Innenausbau",
      "ordinal": 6,
      "taskCount": 4,
      "firstStart": "2026-07-17",
      "lastEnd": "2026-09-08"
    },
    {
      "key": "endausbau",
      "name": "Endausbau",
      "ordinal": 7,
      "taskCount": 7,
      "firstStart": "2026-07-29",
      "lastEnd": "2026-10-13"
    },
    {
      "key": "aussenanlagen",
      "name": "Außenanlagen",
      "ordinal": 8,
      "taskCount": 1,
      "firstStart": "2026-06-30",
      "lastEnd": "2026-07-13"
    },
    {
      "key": "abnahme",
      "name": "Abnahme und Übergabe",
      "ordinal": 9,
      "taskCount": 3,
      "firstStart": "2026-10-14",
      "lastEnd": "2026-10-19"
    }
  ],
  "tasks": [
    {
      "id": "00000000-0000-4000-8000-000000000100",
      "name": "Baugrundgutachten",
      "phaseKey": "vorbereitung",
      "tradeCode": "gutachter",
      "tradeName": "Gutachter",
      "sortOrder": 10,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 10,
      "durationUnit": "werktage",
      "currentStart": "2026-04-01",
      "currentEnd": "2026-04-16",
      "baselineStart": "2026-04-01",
      "baselineEnd": "2026-04-16",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 128,
      "isCritical": false,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000101",
      "name": "Vermessung, Absteckung, Schnurgerüst",
      "phaseKey": "vorbereitung",
      "tradeCode": "vermesser",
      "tradeName": "Vermesser",
      "sortOrder": 20,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 1,
      "durationUnit": "werktage",
      "currentStart": "2026-04-01",
      "currentEnd": "2026-04-01",
      "baselineStart": "2026-04-01",
      "baselineEnd": "2026-04-01",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000102",
      "name": "Baustelleneinrichtung, Bauwasser, Baustrom",
      "phaseKey": "vorbereitung",
      "tradeCode": "gu",
      "tradeName": "Generalunternehmer",
      "sortOrder": 30,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 2,
      "durationUnit": "werktage",
      "currentStart": "2026-04-02",
      "currentEnd": "2026-04-07",
      "baselineStart": "2026-04-02",
      "baselineEnd": "2026-04-07",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000103",
      "name": "Erdarbeiten, Baugrube",
      "phaseKey": "gruendung",
      "tradeCode": "erdbau",
      "tradeName": "Erdbau",
      "sortOrder": 40,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 3,
      "durationUnit": "werktage",
      "currentStart": "2026-04-08",
      "currentEnd": "2026-04-10",
      "baselineStart": "2026-04-08",
      "baselineEnd": "2026-04-10",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000104",
      "name": "Sauberkeitsschicht, Fundamenterder",
      "phaseKey": "gruendung",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 50,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 2,
      "durationUnit": "werktage",
      "currentStart": "2026-04-13",
      "currentEnd": "2026-04-14",
      "baselineStart": "2026-04-13",
      "baselineEnd": "2026-04-14",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "bodenplatte",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000105",
      "name": "Bodenplatte",
      "phaseKey": "gruendung",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 60,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-04-15",
      "currentEnd": "2026-04-20",
      "baselineStart": "2026-04-15",
      "baselineEnd": "2026-04-20",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "bodenplatte",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000106",
      "name": "Aushärtung Bodenplatte",
      "phaseKey": "gruendung",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 70,
      "isMilestone": false,
      "isWait": true,
      "durationDays": 3,
      "durationUnit": "kalendertage",
      "currentStart": "2026-04-21",
      "currentEnd": "2026-04-23",
      "baselineStart": "2026-04-21",
      "baselineEnd": "2026-04-23",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000107",
      "name": "Kellerwände",
      "phaseKey": "gruendung",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 80,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-04-24",
      "currentEnd": "2026-05-06",
      "baselineStart": "2026-04-24",
      "baselineEnd": "2026-05-06",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000108",
      "name": "Kellerdecke",
      "phaseKey": "gruendung",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 90,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-05-07",
      "currentEnd": "2026-05-12",
      "baselineStart": "2026-05-07",
      "baselineEnd": "2026-05-12",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000109",
      "name": "Abdichtung, Perimeterdämmung, Drainage",
      "phaseKey": "gruendung",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 100,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 3,
      "durationUnit": "werktage",
      "currentStart": "2026-05-13",
      "currentEnd": "2026-05-18",
      "baselineStart": "2026-05-13",
      "baselineEnd": "2026-05-18",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 106,
      "isCritical": false,
      "guideCardKey": "kellerabdichtung",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000110",
      "name": "Verfüllung Arbeitsraum",
      "phaseKey": "gruendung",
      "tradeCode": "erdbau",
      "tradeName": "Erdbau",
      "sortOrder": 110,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 2,
      "durationUnit": "werktage",
      "currentStart": "2026-05-19",
      "currentEnd": "2026-05-20",
      "baselineStart": "2026-05-19",
      "baselineEnd": "2026-05-20",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 106,
      "isCritical": false,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000111",
      "name": "Erdgeschoss-Mauerwerk",
      "phaseKey": "rohbau",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 120,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-05-13",
      "currentEnd": "2026-05-26",
      "baselineStart": "2026-05-13",
      "baselineEnd": "2026-05-26",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "disputed",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "rohbau-mauerwerk",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000112",
      "name": "Geschossdecke EG",
      "phaseKey": "rohbau",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 130,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-05-27",
      "currentEnd": "2026-06-01",
      "baselineStart": "2026-05-27",
      "baselineEnd": "2026-06-01",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000113",
      "name": "Obergeschoss, Drempel, Ringanker",
      "phaseKey": "rohbau",
      "tradeCode": "rohbau",
      "tradeName": "Rohbau",
      "sortOrder": 140,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 7,
      "durationUnit": "werktage",
      "currentStart": "2026-06-02",
      "currentEnd": "2026-06-11",
      "baselineStart": "2026-06-02",
      "baselineEnd": "2026-06-11",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "rohbau-mauerwerk",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000114",
      "name": "Rohbau fertig, Richtfest",
      "phaseKey": "rohbau",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 150,
      "isMilestone": true,
      "isWait": false,
      "durationDays": 0,
      "durationUnit": "werktage",
      "currentStart": "2026-06-12",
      "currentEnd": "2026-06-12",
      "baselineStart": "2026-06-12",
      "baselineEnd": "2026-06-12",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000115",
      "name": "Dachstuhl",
      "phaseKey": "dach_huelle",
      "tradeCode": "zimmerer",
      "tradeName": "Zimmerer",
      "sortOrder": 160,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-06-15",
      "currentEnd": "2026-06-18",
      "baselineStart": "2026-06-15",
      "baselineEnd": "2026-06-18",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "dachstuhl",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000116",
      "name": "Dacheindeckung, Klempnerarbeiten",
      "phaseKey": "dach_huelle",
      "tradeCode": "dachdecker",
      "tradeName": "Dachdecker",
      "sortOrder": 170,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 6,
      "durationUnit": "werktage",
      "currentStart": "2026-06-19",
      "currentEnd": "2026-06-26",
      "baselineStart": "2026-06-19",
      "baselineEnd": "2026-06-26",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "dachstuhl",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000117",
      "name": "Fenster und Haustür",
      "phaseKey": "dach_huelle",
      "tradeCode": "fensterbau",
      "tradeName": "Fensterbau",
      "sortOrder": 180,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 3,
      "durationUnit": "werktage",
      "currentStart": "2026-06-19",
      "currentEnd": "2026-06-23",
      "baselineStart": "2026-06-19",
      "baselineEnd": "2026-06-23",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 3,
      "isCritical": false,
      "guideCardKey": "fenster",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000118",
      "name": "Gebäude dicht",
      "phaseKey": "dach_huelle",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 190,
      "isMilestone": true,
      "isWait": false,
      "durationDays": 0,
      "durationUnit": "werktage",
      "currentStart": "2026-06-29",
      "currentEnd": "2026-06-29",
      "baselineStart": "2026-06-29",
      "baselineEnd": "2026-06-29",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000119",
      "name": "Rohinstallation Elektro",
      "phaseKey": "rohinstallation",
      "tradeCode": "elektro",
      "tradeName": "Elektro",
      "sortOrder": 200,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-06-30",
      "currentEnd": "2026-07-09",
      "baselineStart": "2026-06-30",
      "baselineEnd": "2026-07-09",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 4,
      "isCritical": false,
      "guideCardKey": "rohinstallation-elektro",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000120",
      "name": "Rohinstallation Sanitär und Heizung",
      "phaseKey": "rohinstallation",
      "tradeCode": "shk",
      "tradeName": "Sanitär, Heizung, Klima",
      "sortOrder": 210,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-06-30",
      "currentEnd": "2026-07-09",
      "baselineStart": "2026-06-30",
      "baselineEnd": "2026-07-09",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "rohinstallation-shk",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000121",
      "name": "Lüftungsanlage",
      "phaseKey": "rohinstallation",
      "tradeCode": "shk",
      "tradeName": "Sanitär, Heizung, Klima",
      "sortOrder": 220,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-07-10",
      "currentEnd": "2026-07-15",
      "baselineStart": "2026-07-10",
      "baselineEnd": "2026-07-15",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000122",
      "name": "Blower-Door-Vorabtest",
      "phaseKey": "rohinstallation",
      "tradeCode": "pruefer",
      "tradeName": "Prüfer",
      "sortOrder": 230,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 1,
      "durationUnit": "werktage",
      "currentStart": "2026-07-16",
      "currentEnd": "2026-07-16",
      "baselineStart": "2026-07-16",
      "baselineEnd": "2026-07-16",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "disputed",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "blower-door",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000123",
      "name": "Innenputz",
      "phaseKey": "ausbau",
      "tradeCode": "putzer",
      "tradeName": "Putzer",
      "sortOrder": 240,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-07-17",
      "currentEnd": "2026-07-28",
      "baselineStart": "2026-07-17",
      "baselineEnd": "2026-07-28",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 2,
      "isCritical": false,
      "guideCardKey": "innenputz",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000124",
      "name": "Trockenbau, Dachgeschossausbau",
      "phaseKey": "ausbau",
      "tradeCode": "trockenbau",
      "tradeName": "Trockenbau",
      "sortOrder": 250,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 10,
      "durationUnit": "werktage",
      "currentStart": "2026-07-17",
      "currentEnd": "2026-07-30",
      "baselineStart": "2026-07-17",
      "baselineEnd": "2026-07-30",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000125",
      "name": "Estrich",
      "phaseKey": "ausbau",
      "tradeCode": "estrich",
      "tradeName": "Estrich",
      "sortOrder": 260,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 3,
      "durationUnit": "werktage",
      "currentStart": "2026-07-31",
      "currentEnd": "2026-08-04",
      "baselineStart": "2026-07-31",
      "baselineEnd": "2026-08-04",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "estrich",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000126",
      "name": "Trocknung bis Belegreife",
      "phaseKey": "ausbau",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 270,
      "isMilestone": false,
      "isWait": true,
      "durationDays": 35,
      "durationUnit": "kalendertage",
      "currentStart": "2026-08-05",
      "currentEnd": "2026-09-08",
      "baselineStart": "2026-08-05",
      "baselineEnd": "2026-09-08",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "estrich",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000127",
      "name": "Fliesenarbeiten",
      "phaseKey": "endausbau",
      "tradeCode": "fliesen",
      "tradeName": "Fliesenleger",
      "sortOrder": 280,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-09-09",
      "currentEnd": "2026-09-18",
      "baselineStart": "2026-09-09",
      "baselineEnd": "2026-09-18",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "fliesen",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000128",
      "name": "Innentüren",
      "phaseKey": "endausbau",
      "tradeCode": "tischler",
      "tradeName": "Tischler",
      "sortOrder": 290,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 3,
      "durationUnit": "werktage",
      "currentStart": "2026-07-29",
      "currentEnd": "2026-07-31",
      "baselineStart": "2026-07-29",
      "baselineEnd": "2026-07-31",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 35,
      "isCritical": false,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000129",
      "name": "Malerarbeiten",
      "phaseKey": "endausbau",
      "tradeCode": "maler",
      "tradeName": "Maler",
      "sortOrder": 300,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 8,
      "durationUnit": "werktage",
      "currentStart": "2026-09-21",
      "currentEnd": "2026-09-30",
      "baselineStart": "2026-09-21",
      "baselineEnd": "2026-09-30",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000130",
      "name": "Bodenbeläge",
      "phaseKey": "endausbau",
      "tradeCode": "bodenleger",
      "tradeName": "Bodenleger",
      "sortOrder": 310,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 5,
      "durationUnit": "werktage",
      "currentStart": "2026-10-01",
      "currentEnd": "2026-10-07",
      "baselineStart": "2026-10-01",
      "baselineEnd": "2026-10-07",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "counterparty_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000131",
      "name": "Treppe",
      "phaseKey": "endausbau",
      "tradeCode": "treppenbau",
      "tradeName": "Treppenbau",
      "sortOrder": 320,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 2,
      "durationUnit": "werktage",
      "currentStart": "2026-10-01",
      "currentEnd": "2026-10-02",
      "baselineStart": "2026-10-01",
      "baselineEnd": "2026-10-02",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 11,
      "isCritical": false,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000132",
      "name": "Endmontage Elektro",
      "phaseKey": "endausbau",
      "tradeCode": "elektro",
      "tradeName": "Elektro",
      "sortOrder": 330,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-10-08",
      "currentEnd": "2026-10-13",
      "baselineStart": "2026-10-08",
      "baselineEnd": "2026-10-13",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000133",
      "name": "Endmontage Sanitär",
      "phaseKey": "endausbau",
      "tradeCode": "shk",
      "tradeName": "Sanitär, Heizung, Klima",
      "sortOrder": 340,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 4,
      "durationUnit": "werktage",
      "currentStart": "2026-10-08",
      "currentEnd": "2026-10-13",
      "baselineStart": "2026-10-08",
      "baselineEnd": "2026-10-13",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "disputed",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000134",
      "name": "Außenanlagen, Zufahrt, Pflaster",
      "phaseKey": "aussenanlagen",
      "tradeCode": "galabau",
      "tradeName": "Garten- und Landschaftsbau",
      "sortOrder": 350,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 10,
      "durationUnit": "werktage",
      "currentStart": "2026-06-30",
      "currentEnd": "2026-07-13",
      "baselineStart": "2026-06-30",
      "baselineEnd": "2026-07-13",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 70,
      "isCritical": false,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000135",
      "name": "Baureinigung",
      "phaseKey": "abnahme",
      "tradeCode": "reinigung",
      "tradeName": "Reinigung",
      "sortOrder": 360,
      "isMilestone": false,
      "isWait": false,
      "durationDays": 2,
      "durationUnit": "werktage",
      "currentStart": "2026-10-14",
      "currentEnd": "2026-10-15",
      "baselineStart": "2026-10-14",
      "baselineEnd": "2026-10-15",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "mutual",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000136",
      "name": "Abnahme und Übergabe",
      "phaseKey": "abnahme",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 370,
      "isMilestone": true,
      "isWait": false,
      "durationDays": 0,
      "durationUnit": "werktage",
      "currentStart": "2026-10-16",
      "currentEnd": "2026-10-16",
      "baselineStart": "2026-10-16",
      "baselineEnd": "2026-10-16",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": "abnahme",
      "guideCardRead": false
    },
    {
      "id": "00000000-0000-4000-8000-000000000137",
      "name": "Schlussrechnung, Restzahlung",
      "phaseKey": "abnahme",
      "tradeCode": null,
      "tradeName": null,
      "sortOrder": 380,
      "isMilestone": true,
      "isWait": false,
      "durationDays": 0,
      "durationUnit": "werktage",
      "currentStart": "2026-10-19",
      "currentEnd": "2026-10-19",
      "baselineStart": "2026-10-19",
      "baselineEnd": "2026-10-19",
      "earliestStart": null,
      "actualStart": null,
      "actualEnd": null,
      "status": "terminiert",
      "confirmation": "self_stated",
      "totalFloatDays": 0,
      "isCritical": true,
      "guideCardKey": null,
      "guideCardRead": false
    }
  ],
  "decisions": [
    {
      "id": "00000000-0000-4000-8000-000000000500",
      "templateKey": "versicherungen",
      "title": "Bauherrenhaftpflicht und Bauleistungsversicherung",
      "description": "Beides muss stehen, bevor die erste Maschine auf das Grundstück fährt. Danach ist es zu spät.",
      "helpText": "Die Bauherrenhaftpflicht deckt Schäden, die von deiner Baustelle ausgehen — ein Passant stürzt in die offene Baugrube, ein Ziegel trifft ein Auto. Als Bauherr haftest du dafür, auch wenn ein Unternehmen gearbeitet hat. Die Bauleistungsversicherung deckt Schäden am Bau selbst, etwa durch Sturm, Vandalismus oder Diebstahl fest eingebauter Teile. Was du später bereust: einen Schaden in den ersten Wochen, weil die Policen erst zum Richtfest abgeschlossen wurden.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000102",
      "blocksTaskName": "Baustelleneinrichtung, Bauwasser, Baustrom",
      "blocksTaskStart": "2026-04-02",
      "leadTimeDays": 10,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-03-19",
      "status": "entschieden",
      "decidedAt": "2026-03-02T10:00:00.000Z",
      "decidedNote": "Beim Termin am 02.03. festgelegt.",
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000501",
      "templateKey": "bauhelfer-bg-bau",
      "title": "Bauhelfer bei der BG Bau anmelden",
      "description": "Wer auf deiner Baustelle unentgeltlich mithilft, ist gesetzlich unfallversichert — und muss gemeldet sein.",
      "helpText": "Sobald Freunde oder Verwandte mit anpacken, bist du Unternehmer im Sinne der gesetzlichen Unfallversicherung. Die Anmeldung bei der Berufsgenossenschaft der Bauwirtschaft ist Pflicht und kostet wenig; ein nicht gemeldeter Helfer, dem etwas passiert, kostet sehr viel. Gemeldet wird vor dem ersten Einsatz, nicht danach. Auch reine Eigenleistung ohne Helfer wird angezeigt.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000102",
      "blocksTaskName": "Baustelleneinrichtung, Bauwasser, Baustrom",
      "blocksTaskStart": "2026-04-02",
      "leadTimeDays": 5,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-03-26",
      "status": "entschieden",
      "decidedAt": "2026-03-02T10:00:00.000Z",
      "decidedNote": "Beim Termin am 02.03. festgelegt.",
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000502",
      "templateKey": "dachziegel",
      "title": "Dachziegel: Modell und Farbe",
      "description": "Die Eindeckung wird bestellt, sobald der Dachstuhl steht.",
      "helpText": "Form und Material bestimmen, welche Dachneigung zulässig ist und wie viel Gewicht der Dachstuhl trägt — beides ist mit der Statik verknüpft und keine reine Geschmacksfrage. Bei der Farbe entscheidet vor allem der Ort: Manche Bebauungspläne schreiben Farbtöne vor. Was du später bereust: eine Sonderfarbe mit langer Lieferzeit, die den ganzen Ausbau schiebt, weil das Haus bis dahin nicht dicht ist.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000116",
      "blocksTaskName": "Dacheindeckung, Klempnerarbeiten",
      "blocksTaskStart": "2026-06-19",
      "leadTimeDays": 20,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-05-20",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": 480000
    },
    {
      "id": "00000000-0000-4000-8000-000000000503",
      "templateKey": "fassade",
      "title": "Fassade: Putz oder Klinker, Farbton",
      "description": "Die Wahl bestimmt, wie lange das Gerüst steht — und was es kostet.",
      "helpText": "Putz ist günstiger und in jeder Farbe zu haben, muss aber alle paar Jahrzehnte erneuert werden. Klinker kostet deutlich mehr, hält dafür ohne Pflege. Beides beeinflusst die Gerüststandzeit, und Gerüst wird nach Zeit berechnet. Prüf den Bebauungsplan, bevor du dich festlegst: Farbton und Material sind dort häufig vorgegeben. Was du später bereust: einen sehr dunklen Ton auf gedämmter Fassade — er heizt sich auf und arbeitet stärker.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000116",
      "blocksTaskName": "Dacheindeckung, Klempnerarbeiten",
      "blocksTaskStart": "2026-06-19",
      "leadTimeDays": 25,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-05-12",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000504",
      "templateKey": "fenster",
      "title": "Fenster: Farbe, Verglasung, Rollladen, Griffe",
      "description": "Fenster werden für dein Haus gefertigt. Zwischen Bestellung und Einbau liegen Wochen.",
      "helpText": "Drei Dinge entscheidest du hier gleichzeitig. Erstens die Verglasung: Zweifach oder Dreifach bestimmt den Wärmeschutz und muss zum Wärmeschutznachweis passen. Zweitens den Sonnenschutz: Rollladen, Raffstore oder nichts — nachträglich ist jeder Rollladenkasten ein Eingriff in die Wand. Drittens die Bedienung: abschließbare Griffe im Erdgeschoss, Fenstertüren mit oder ohne Schwelle. Was du später bereust: eine Sonderfarbe außen, die drei Wochen extra Lieferzeit kostet, und fehlende Verschattung nach Süden — die erste Hitzewelle beantwortet die Frage von selbst.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000117",
      "blocksTaskName": "Fenster und Haustür",
      "blocksTaskStart": "2026-06-19",
      "leadTimeDays": 60,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-03-19",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000505",
      "templateKey": "elektroplanung",
      "title": "Elektroplanung: Steckdosen, Schalter, Netzwerk",
      "description": "Nach dem Schlitzen der Wände ist jede zusätzliche Dose ein Nachtrag mit Staub.",
      "helpText": "Geh vor dem Termin mit dem Elektriker gedanklich durch jeden Raum und stell die Möbel auf: Wo steht das Bett, wo der Fernseher, wo der Schreibtisch. Eine Steckdose hinter dem Schrank ist verloren, eine fehlende neben dem Bett ärgert zehn Jahre lang. Denk an das, was du noch nicht hast: Leerrohre für Wallbox, Photovoltaik, Außenbeleuchtung und Netzwerk kosten jetzt fast nichts. Was du später bereust: nach Mindestausstattung geplant zu haben — sie ist ein Minimum, kein Vorschlag.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000119",
      "blocksTaskName": "Rohinstallation Elektro",
      "blocksTaskStart": "2026-06-30",
      "leadTimeDays": 15,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-06-09",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000506",
      "templateKey": "kueche",
      "title": "Küchenplanung mit Anschlusspunkten",
      "description": "Starkstrom, Wasser und Abluft müssen liegen, bevor die Wände geschlossen werden.",
      "helpText": "Die Küche wird zwar zuletzt geliefert, aber ihre Anschlüsse entstehen jetzt. Du brauchst dafür keine fertige Küche, sondern einen Plan mit Positionen: Herd, Spüle, Geschirrspüler, Kühlschrank, Dunstabzug. Kläre früh, ob abgesaugt oder umgeluftet wird — eine Außenwanddurchführung ist nachträglich eine Kernbohrung. Was du später bereust: eine Kücheninsel ohne Anschluss darunter, weil sie erst nach dem Estrich beschlossen wurde.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000119",
      "blocksTaskName": "Rohinstallation Elektro",
      "blocksTaskStart": "2026-06-30",
      "leadTimeDays": 20,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-06-01",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000507",
      "templateKey": "heizsystem",
      "title": "Heizsystem und Wärmepumpe final",
      "description": "Lieferzeit und Förderantrag brauchen beide Vorlauf, und zwar nacheinander.",
      "helpText": "Die Wahl des Wärmeerzeugers hängt am Wärmeschutznachweis und an der Heizlast, nicht am Geschmack. Wichtig ist die Reihenfolge: Ein Förderantrag wird vor dem Auftrag gestellt, sonst entfällt die Förderung — nachträglich lässt sich das nicht heilen. Klär außerdem den Aufstellort und die Abstände zum Nachbargrundstück, denn Wärmepumpen erzeugen Geräusche und dafür gelten Grenzwerte. Was du später bereust: die Anlage bestellt zu haben, bevor der Antrag durch war.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000120",
      "blocksTaskName": "Rohinstallation Sanitär und Heizung",
      "blocksTaskStart": "2026-06-30",
      "leadTimeDays": 40,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-04-29",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000508",
      "templateKey": "sanitaerobjekte",
      "title": "Sanitärobjekte und Vorwandpositionen",
      "description": "Wo die Objekte hängen, entscheidet sich beim Stellen der Vorwand.",
      "helpText": "Es geht nicht um Armaturen und Farben, sondern um Maße: Wandhängendes WC oder bodenstehend, Dusche bodengleich oder mit Wanne, Waschtisch als Möbel oder als Becken. Jede Variante hat andere Anschlusshöhen. Steh einmal im Rohbau im Bad und stell dir die Objekte vor — auf dem Plan wirkt jedes Bad größer als es ist. Was du später bereust: eine bodengleiche Dusche, die erst nach dem Estrich gewünscht wurde; die Bodenplatte gibt die Höhe dann nicht mehr her.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000120",
      "blocksTaskName": "Rohinstallation Sanitär und Heizung",
      "blocksTaskStart": "2026-06-30",
      "leadTimeDays": 20,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-06-01",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000509",
      "templateKey": "bodenbelag",
      "title": "Bodenbelag und Aufbauhöhe",
      "description": "Die Aufbauhöhe bestimmt den Estrich — und der kommt zuerst.",
      "helpText": "Fliesen, Parkett und Vinyl bauen unterschiedlich hoch auf. Diese Höhe geht in die Estrichdicke ein, und die wiederum in die Höhe der Türen und der Übergänge zwischen den Räumen. Deshalb wird der Belag ausgewählt, bevor der Estrich eingebracht wird, auch wenn er erst Monate später verlegt wird. Was du später bereust: unterschiedliche Beläge in angrenzenden Räumen ohne geplanten Höhenausgleich — die Stufe im Türrahmen bleibt.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000125",
      "blocksTaskName": "Estrich",
      "blocksTaskStart": "2026-07-31",
      "leadTimeDays": 15,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-07-10",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000510",
      "templateKey": "fliesen",
      "title": "Fliesen: Auswahl und Verlegemuster",
      "description": "Der häufigste Grund für Verzug im Innenausbau. Fliesen sind Lagerware oder eben nicht.",
      "helpText": "Entscheide früher, als es sich anfühlt: Zwischen Aussuchen und Verlegen liegen Bemusterung, Bestellung und Lieferung, und bei Sonderformaten sind das schnell zwei Monate. Neben der Fliese selbst gehören zwei Dinge dazu: das Verlegemuster, das bestimmt, wo die Schnitte landen, und die Fugenfarbe, die das Bild stärker verändert als die meisten erwarten. Was du später bereust: eine schmale Restreihe in der Sichtachse, weil kein Verlegeplan gemacht wurde.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000127",
      "blocksTaskName": "Fliesenarbeiten",
      "blocksTaskStart": "2026-09-09",
      "leadTimeDays": 40,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-07-15",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000511",
      "templateKey": "innentueren",
      "title": "Innentüren: Modell, Zargen, Beschläge",
      "description": "Lange Lieferzeiten, und die Zargen brauchen das Maß aus dem Rohbau.",
      "helpText": "Türblatt, Zarge und Beschlag werden zusammen bestellt und zusammen geliefert. Die Zargenbreite hängt an der fertigen Wandstärke, also an Putz und Estrichaufbau — deshalb wird nach dem Rohbau aufgemessen. Denk an die Details, die man erst im Alltag merkt: Türen, die in den Raum oder aus ihm heraus aufgehen, Lichtausschnitte in dunklen Fluren, Schwellen bei bodengleichen Übergängen. Was du später bereust: eine Standardhöhe, die nicht zur Deckenhöhe passt, oder fehlende Lüftungsspalte bei kontrollierter Wohnraumlüftung.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000128",
      "blocksTaskName": "Innentüren",
      "blocksTaskStart": "2026-07-29",
      "leadTimeDays": 50,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-05-18",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000512",
      "templateKey": "treppe",
      "title": "Treppe: Material und Geländer",
      "description": "Aufgemessen wird am Rohbau, gefertigt wird danach — beides braucht Zeit.",
      "helpText": "Die Treppe ist ein Möbelstück und wird für deinen Rohbau gebaut. Material und Bauart bestimmen den Preis stärker als die Größe: Beton mit Belag, Holz eingestemmt oder eine freitragende Konstruktion sind drei verschiedene Welten. Beim Geländer gelten Vorschriften zu Höhe und Abstand, die nicht verhandelbar sind. Was du später bereust: eine offene Treppe ohne Setzstufen im Haus mit kleinen Kindern, und eine Wahl, die den Schallschutz nicht berücksichtigt — eine Holztreppe überträgt jeden Schritt.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000131",
      "blocksTaskName": "Treppe",
      "blocksTaskStart": "2026-10-01",
      "leadTimeDays": 50,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-07-23",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000513",
      "templateKey": "aussenanlagen",
      "title": "Außenanlagen: Zufahrt, Terrasse, Zaun",
      "description": "Das Letzte am Bau, und regelmäßig das, wofür das Geld nicht mehr reicht.",
      "helpText": "Plan die Außenanlagen früh, auch wenn sie zuletzt gebaut werden: Zufahrt, Stellplätze, Terrasse, Wege und Einfriedung summieren sich zu einem fünfstelligen Betrag, der in vielen Baubeschreibungen gar nicht enthalten ist. Kläre nebenbei zwei Dinge, die Vorlauf brauchen: die Entwässerung des Niederschlagswassers, für die es kommunale Vorgaben gibt, und Leerrohre für Außensteckdosen und Licht, solange der Graben noch offen ist. Was du später bereust: gepflastert zu haben, bevor die letzten schweren Fahrzeuge auf dem Grundstück waren.",
      "blocksTaskId": "00000000-0000-4000-8000-000000000134",
      "blocksTaskName": "Außenanlagen, Zufahrt, Pflaster",
      "blocksTaskStart": "2026-06-30",
      "leadTimeDays": 25,
      "leadTimeUnit": "werktage",
      "dueDate": "2026-05-22",
      "status": "offen",
      "decidedAt": null,
      "decidedNote": null,
      "estimatedCostCents": null
    }
  ],
  "computedEnd": "2026-10-19",
  "contractualEnd": "2026-09-30",
  "deviationWorkdays": 13
};

export const GUIDE_CARD_FIXTURE: GuideCardView = {
  "card": {
    "id": "00000000-0000-4000-8000-000000000900",
    "key": "estrich",
    "version": 1,
    "title": "Estrich und Belegreife",
    "phaseKey": "ausbau",
    "tradeCode": "estrich",
    "whatsHappening": "Auf die Rohdecke kommen Dämmung, Folie und darauf der Estrich — die Schicht, die später den Bodenbelag trägt. Danach folgt die Trocknung bis zur Belegreife: dem Zustand, in dem der Estrich trocken genug ist, dass ein Belag darauf verlegt werden darf.\n\nDiese Trocknung ist Wartezeit, keine Pufferzeit. Sie steht als eigener Vorgang in deinem Plan und lässt sich nicht verkürzen, indem jemand schneller arbeitet.",
    "watchFor": [
      {
        "text": "Ringsum an allen Wänden steht ein Randdämmstreifen, auch an Türzargen und Rohren",
        "why": "ohne ihn überträgt der Estrich Trittschall in die Wände"
      },
      {
        "text": "Die Aufbauhöhe passt zum Belag, den du ausgesucht hast",
        "why": "Fliesen und Parkett bauen unterschiedlich hoch, und die Türen sind schon bestellt"
      },
      {
        "text": "Die Bewegungsfugen liegen nach Plan, insbesondere in Türdurchgängen",
        "why": "ein Estrich ohne Fugenplan reißt an der ungünstigsten Stelle von selbst"
      },
      {
        "text": "Bei Fußbodenheizung wird das vorgeschriebene Aufheizprogramm gefahren und protokolliert",
        "why": "ohne dieses Protokoll verweigert mancher Bodenleger die Verlegung"
      },
      {
        "text": "Die Belegreife wird gemessen und nicht geschätzt",
        "why": "die Messung ist eine Zahl auf einem Protokoll, kein Blick auf den Boden"
      }
    ],
    "questionsForContractor": [
      {
        "question": "Welcher Estrich wird eingebaut, und welche Aufbauhöhe hat er?",
        "whyItMatters": "Zement- und Calciumsulfatestrich trocknen unterschiedlich lang und vertragen unterschiedlich viel Feuchte"
      },
      {
        "question": "Wann wird die Belegreife gemessen, mit welchem Verfahren und wer bekommt das Protokoll?",
        "whyItMatters": "üblich ist die CM-Messung, und der Grenzwert hängt von Estrichart und Fußbodenheizung ab"
      },
      {
        "question": "Gibt es einen Fugenplan, und wo liegen die Fugen?",
        "whyItMatters": "die Lage der Fugen bestimmt später das Verlegebild"
      },
      {
        "question": "Wie wird während der Trocknung gelüftet und geheizt?",
        "whyItMatters": "falsches Lüften in den ersten Tagen führt zu Rissen"
      }
    ],
    "commonProblems": [
      {
        "problem": "Zu früh belegt, weil der Termin drängte",
        "howToSpot": "der Belag wirft Wellen oder löst sich, und die Ursache ist erst nach dem Herausreißen sichtbar"
      },
      {
        "problem": "Der Randdämmstreifen wird zu früh abgeschnitten oder fehlt hinter Zargen",
        "howToSpot": "es entstehen Schallbrücken, die man hört und nicht mehr beheben kann"
      },
      {
        "problem": "Die Aufbauhöhe passt nicht zum Belag",
        "howToSpot": "Türen schleifen oder es entsteht eine Stufe zum Nachbarraum"
      },
      {
        "problem": "Das Aufheizprotokoll fehlt",
        "howToSpot": "der Bodenleger legt nicht los, und der Termin verschiebt sich um Wochen"
      }
    ],
    "photoPrompts": [
      {
        "what": "Die verlegte Dämmung mit allen Leitungen darin, vor dem Estrich",
        "why": "danach weiß niemand mehr, wo etwas liegt"
      },
      {
        "what": "Die Heizkreise der Fußbodenheizung, raumweise",
        "why": "beim späteren Bohren in den Boden ist das der einzige Anhaltspunkt"
      },
      {
        "what": "Der Randdämmstreifen an den Wänden",
        "why": "er verschwindet unter Sockelleiste und Belag"
      }
    ],
    "expertRecommended": false,
    "expertReason": null,
    "sources": [
      {
        "reference": "DIN 18560-1 und -2",
        "note": "Estriche im Bauwesen, unter anderem Estriche auf Dämmschichten"
      },
      {
        "reference": "Schnittstellenkoordination der Verbände von Estrich-, Fliesen- und Parkettgewerk",
        "note": "Belegreife und CM-Messung"
      },
      {
        "reference": "DIN 18202",
        "note": "Toleranzen im Hochbau, Ebenheit von Bodenflächen"
      },
      {
        "reference": "VOB/C ATV DIN 18353",
        "note": "Estricharbeiten, sofern die VOB/B vereinbart ist"
      }
    ]
  },
  "taskId": "00000000-0000-4000-8000-000000000125",
  "taskName": "Estrich",
  "checklist": [
    {
      "id": "00000000-0000-4000-8000-000000000910",
      "text": "Ringsum an allen Wänden steht ein Randdämmstreifen, auch an Türzargen und Rohren",
      "why": "ohne ihn überträgt der Estrich Trittschall in die Wände",
      "sortOrder": 0,
      "isDone": true,
      "doneAt": "2026-07-30T09:12:00.000Z",
      "note": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000911",
      "text": "Die Aufbauhöhe passt zum Belag, den du ausgesucht hast",
      "why": "Fliesen und Parkett bauen unterschiedlich hoch, und die Türen sind schon bestellt",
      "sortOrder": 1,
      "isDone": false,
      "doneAt": null,
      "note": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000912",
      "text": "Die Bewegungsfugen liegen nach Plan, insbesondere in Türdurchgängen",
      "why": "ein Estrich ohne Fugenplan reißt an der ungünstigsten Stelle von selbst",
      "sortOrder": 2,
      "isDone": false,
      "doneAt": null,
      "note": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000913",
      "text": "Bei Fußbodenheizung wird das vorgeschriebene Aufheizprogramm gefahren und protokolliert",
      "why": "ohne dieses Protokoll verweigert mancher Bodenleger die Verlegung",
      "sortOrder": 3,
      "isDone": false,
      "doneAt": null,
      "note": null
    },
    {
      "id": "00000000-0000-4000-8000-000000000914",
      "text": "Die Belegreife wird gemessen und nicht geschätzt",
      "why": "die Messung ist eine Zahl auf einem Protokoll, kein Blick auf den Boden",
      "sortOrder": 4,
      "isDone": false,
      "doneAt": null,
      "note": null
    }
  ],
  "read": null,
  "canCheck": true
};
